<?xml version="1.0" encoding="utf-8"?><Database Name="LVN" Class="DataSachDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-8DT63HU\MSSQLSERVER01;Initial Catalog=LVN;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="Login.Properties.Settings" SettingsPropertyName="LVNConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DocGia" Member="DocGias">
    <Type Name="DocGia">
      <Column Name="SoThe" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Khoa" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="DocGia_LichSuMuonTraSach" Member="LichSuMuonTraSaches" ThisKey="SoThe" OtherKey="SoThe" Type="LichSuMuonTraSach" />
    </Type>
  </Table>
  <Table Name="dbo.LichSuMuonTraSach" Member="LichSuMuonTraSaches">
    <Type Name="LichSuMuonTraSach">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SoThe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayMuon" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayTra" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="DocGia_LichSuMuonTraSach" Member="DocGia" ThisKey="SoThe" OtherKey="SoThe" Type="DocGia" IsForeignKey="true" />
      <Association Name="Sach_LichSuMuonTraSach" Member="Sach" ThisKey="MaSach" OtherKey="MaSach" Type="Sach" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sach" Member="Saches">
    <Type Name="Sach">
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenSach" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="TacGia" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="TheLoai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NamXuatBan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GiaSach" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Sach_LichSuMuonTraSach" Member="LichSuMuonTraSaches" ThisKey="MaSach" OtherKey="MaSach" Type="LichSuMuonTraSach" />
    </Type>
  </Table>
</Database>